services:
  - type: web
    name: sillicon-helpdesk
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://zk00465_db_user:bxridmjTB4li1rtv@cluster0.hgplvh3.mongodb.net/helpdesk_mini?retryWrites=true&w=majority

  - type: web
    name: sillicon-helpdesk-client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    publishDir: client/dist